[#1229] adding dynamo events build command in circle ci Adding user fields and signed_on field in dbModel of signatures implementing function GetClaGroupICLASignatures adding new api listClaGroupIclaSignature
Signed-off-by: prasanna.mahajan <mahajanprasannap@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -171,6 +171,7 @@ jobs:
             cd cla-backend-go
             make build-aws-lambda
             make build-metrics-lambda
+            make build-dynamo-events-lambda
             make build-functional-tests-linux
       - run:
           name: Test
@@ -191,6 +192,7 @@ jobs:
           paths:
             - cla-backend-go/backend-aws-lambda
             - cla-backend-go/metrics-aws-lambda
+            - cla-backend-go/dynamo-events-lambda
             - cla-backend-go/functional-tests
 
   buildGoBackendDev:
@@ -264,6 +266,7 @@ jobs:
             # Copy over the go backend binary to the common cla-backend folder (they share a single serverless.yml config)
             cp ~/cla-backend-go/backend-aws-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/metrics-aws-lambda ~/project/cla-backend/
+            cp ~/cla-backend-go/dynamo-events-lambda ~/project/cla-backend/
 
             ls -alF ~/project/cla-backend/
             pushd ~/project/cla-backend
@@ -272,6 +275,7 @@ jobs:
 
             if [[ ! -f backend-aws-lambda ]]; then echo "Missing backend-aws-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f metrics-aws-lambda ]]; then echo "Missing metrics-aws-lambda binary file. Exiting..."; exit 1; fi
+            if [[ ! -f dynamo-events-lambda ]]; then echo "Missing dynamo-events-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f serverless.yml ]]; then echo "Missing serverless.yml file. Exiting..."; exit 1; fi
             if [[ ! -f serverless-authorizer.yml ]]; then echo "Missing serverless-authorizer.yml file. Exiting..."; exit 1; fi
             yarn sls deploy --force --stage ${STAGE} --region us-east-1
