Updated GitHub Comment Logic
- Updated comment check logic
- Updated success formatting - added break
- Updated CI/CD for metrics report lambda

Signed-off-by: David Deal <dealako@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -237,8 +237,10 @@ jobs:
             cd cla-backend-go
             echo "Building AWS Lambda - API..."
             make build-aws-lambda-linux
-            echo "Building AWS Lambda - Metrics..."
+            echo "Building AWS Metrics Lambda..."
             make build-metrics-lambda-linux
+            echo "Building AWS Metrics Report Lambda..."
+            make build-metrics-report-lambda
             echo "Building AWS Lambda - DynamoDB Events Handler..."
             make build-dynamo-events-lambda-linux
             echo "Building AWS Lambda - Zip Builder Scheduler..."
@@ -269,6 +271,7 @@ jobs:
             - cla-backend-go/backend-aws-lambda
             - cla-backend-go/user-subscribe-lambda
             - cla-backend-go/metrics-aws-lambda
+            - cla-backend-go/metrics-report-lambda
             - cla-backend-go/dynamo-events-lambda
             - cla-backend-go/zipbuilder-scheduler-lambda
             - cla-backend-go/zipbuilder-lambda
@@ -328,6 +331,7 @@ jobs:
             cp ~/cla-backend-go/backend-aws-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/user-subscribe-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/metrics-aws-lambda ~/project/cla-backend/
+            cp ~/cla-backend-go/metrics-report-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/dynamo-events-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/zipbuilder-scheduler-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/zipbuilder-lambda ~/project/cla-backend/
@@ -340,6 +344,7 @@ jobs:
             if [[ ! -f backend-aws-lambda ]]; then echo "Missing backend-aws-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f user-subscribe-lambda ]]; then echo "Missing user-subscribe-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f metrics-aws-lambda ]]; then echo "Missing metrics-aws-lambda binary file. Exiting..."; exit 1; fi
+            if [[ ! -f metrics-report-lambda ]]; then echo "Missing metrics-report-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f dynamo-events-lambda ]]; then echo "Missing dynamo-events-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f zipbuilder-lambda ]]; then echo "Missing zipbuilder-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f zipbuilder-scheduler-lambda ]]; then echo "Missing zipbuilder-scheduler-lambda binary file. Exiting..."; exit 1; fi
