[#1227] copying zipbuilder binary files in v2 serverless block
Signed-off-by: prasanna.mahajan <mahajanprasannap@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -273,8 +273,6 @@ jobs:
             cp ~/cla-backend-go/backend-aws-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/metrics-aws-lambda ~/project/cla-backend/
             cp ~/cla-backend-go/dynamo-events-lambda ~/project/cla-backend/
-            cp ~/cla-backend-go/zipbuilder-schedular-lambda ~/project/cla-backend/
-            cp ~/cla-backend-go/zipbuilder-lambda ~/project/cla-backend/
 
             ls -alF ~/project/cla-backend/
             pushd ~/project/cla-backend
@@ -284,8 +282,6 @@ jobs:
             if [[ ! -f backend-aws-lambda ]]; then echo "Missing backend-aws-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f metrics-aws-lambda ]]; then echo "Missing metrics-aws-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f dynamo-events-lambda ]]; then echo "Missing dynamo-events-lambda binary file. Exiting..."; exit 1; fi
-            if [[ ! -f zipbuilder-lambda ]]; then echo "Missing zipbuilder-lambda binary file. Exiting..."; exit 1; fi
-            if [[ ! -f zipbuilder-schedular-lambda ]]; then echo "Missing zipbuilder-schedular-lambda binary file. Exiting..."; exit 1; fi
             if [[ ! -f serverless.yml ]]; then echo "Missing serverless.yml file. Exiting..."; exit 1; fi
             if [[ ! -f serverless-authorizer.yml ]]; then echo "Missing serverless-authorizer.yml file. Exiting..."; exit 1; fi
             yarn sls deploy --force --stage ${STAGE} --region us-east-1
@@ -305,11 +301,15 @@ jobs:
             # --------------------------------------------------------------
 
             cp ~/cla-backend-go/backend-aws-lambda ~/project/cla-backend-go/
+            cp ~/cla-backend-go/zipbuilder-schedular-lambda ~/project/cla-backend/
+            cp ~/cla-backend-go/zipbuilder-lambda ~/project/cla-backend/
             echo "Directory: ~/project/cla-backend-go/"
             ls -alF ~/project/cla-backend-go/
             pushd ~/project/cla-backend-go
             echo "Directory: $(pwd)"
             if [[ ! -f backend-aws-lambda ]]; then echo "Missing backend-aws-lambda binary file. Exiting..."; exit 1; fi
+            if [[ ! -f zipbuilder-lambda ]]; then echo "Missing zipbuilder-lambda binary file. Exiting..."; exit 1; fi
+            if [[ ! -f zipbuilder-schedular-lambda ]]; then echo "Missing zipbuilder-schedular-lambda binary file. Exiting..."; exit 1; fi
             yarn install
 
             # Deploy to us-east-2
