Try to fix the deployment 33
Signed-off-by: Lukasz Gryglicki <lgryglicki@cncf.io>

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -165,16 +165,6 @@ jobs:
           declare -r v2_url="https://api.lfcla.${STAGE}.platform.linuxfoundation.org/v2/health"
           declare -r v3_url="https://api.lfcla.${STAGE}.platform.linuxfoundation.org/v3/ops/health"
 
-          echo "Validating v2 backend using endpoint: ${v2_url}"
-          curl --fail -XGET ${v2_url}
-          exit_code=$?
-          if [[ ${exit_coe} -eq 0 ]]; then
-            echo "Successful response from endpoint: ${v2_url}"
-          else
-            echo "Failed to get a successful response from endpoint: ${v2_url}"
-            exit ${exit_code}
-          fi
-
           echo "Validating v3 backend using endpoint: ${v3_url}"
           curl --fail -XGET ${v3_url}
           exit_code=$?
@@ -191,6 +181,17 @@ jobs:
             echo "Failed to get a successful response from endpoint: ${v3_url}"
             exit ${exit_code}
           fi
+
+          echo "Validating v2 backend using endpoint: ${v2_url}"
+          curl --fail -XGET ${v2_url}
+          exit_code=$?
+          if [[ ${exit_coe} -eq 0 ]]; then
+            echo "Successful response from endpoint: ${v2_url}"
+          else
+            echo "Failed to get a successful response from endpoint: ${v2_url}"
+            exit ${exit_code}
+          fi
+
       - name: EasyCLA v2 Deployment us-east-2
         working-directory: cla-backend-go
         run: |
