Try to fix the deployment 41
Signed-off-by: Lukasz Gryglicki <lgryglicki@cncf.io>

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -123,8 +123,7 @@ jobs:
 
       - name: Go Lint
         working-directory: cla-backend-go
-        run: |
-          make lint
+        run: make lint
 
       - name: Setup Deployment
         working-directory: cla-backend
@@ -164,6 +163,16 @@ jobs:
           declare -r v2_url="https://api.lfcla.${STAGE}.platform.linuxfoundation.org/v2/health"
           declare -r v3_url="https://api.lfcla.${STAGE}.platform.linuxfoundation.org/v3/ops/health"
 
+          echo "Validating v2 backend using endpoint: ${v2_url}"
+          curl --fail -XGET ${v2_url}
+          exit_code=$?
+          if [[ ${exit_coe} -eq 0 ]]; then
+            echo "Successful response from endpoint: ${v2_url}"
+          else
+            echo "Failed to get a successful response from endpoint: ${v2_url}"
+            exit ${exit_code}
+          fi
+
           echo "Validating v3 backend using endpoint: ${v3_url}"
           curl --fail -XGET ${v3_url}
           exit_code=$?
@@ -181,23 +190,12 @@ jobs:
             exit ${exit_code}
           fi
 
-          echo "Validating v2 backend using endpoint: ${v2_url}"
-          curl --fail -XGET ${v2_url}
-          exit_code=$?
-          if [[ ${exit_coe} -eq 0 ]]; then
-            echo "Successful response from endpoint: ${v2_url}"
-          else
-            echo "Failed to get a successful response from endpoint: ${v2_url}"
-            exit ${exit_code}
-          fi
-
       - name: EasyCLA v2 Deployment us-east-2
         working-directory: cla-backend-go
         run: |
           if [[ ! -f bin/backend-aws-lambda ]]; then echo "Missing bin/backend-aws-lambda binary file. Exiting..."; exit 1; fi
           if [[ ! -f bin/user-subscribe-lambda ]]; then echo "Missing bin/user-subscribe-lambda binary file. Exiting..."; exit 1; fi
           # rm -rf ./node_modules/
-          find .
           yarn install
           yarn sls deploy --force --stage ${STAGE} --region us-east-2 --verbose
 
